version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}